# List all environments in use
environments:
  - development
  - test
  - production

# Choose environment
environment: development

# Paths (relative to ./controllers) to the views and public folders
views_path:      '../views'
public_path:     '../public'
migrations_path: './database/migrations'

# Development specific settings
development:
  sqlite_path: 'database/jobs-for-charity.db'
